name: Go Test Report

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.5'

    - name: Run tests with JSON output
      run: |
        go test ./... -json > test.json

    - name: Generate test report
      run: |
        go run main.go test.json

    - uses: mshick/add-pr-comment@v2
      with:
        message-id: test-report
        message-path: test_report.md