name: Go Test Report

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: write
  pages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false

    - name: Run tests with JSON output
      run: |
        go test ./... -json > test-output.json || true

    - name: Generate and Comment Test Report
      uses: ./
      with:
        test-json-file: test-output.json
        output-file: test-report.md
        comment-pr: true
        fail-on-test-failure: false

    - name: Publish Test Results to Wiki
      # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        chmod +x ./publish_results_wiki.sh
        ./publish_results_wiki.sh test-report.md "Latest-Test-Results"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
