name: Go Test Report

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.5'

    - name: Run tests with JSON output
      run: |
        mkdir -p test-results
        go test ./... -json > test-results/test.json || true

    - name: Generate test report
      run: |
        go run main.go test-results/test.json || exit 1

    - name: Read test report
      id: report
      run: |
        if [ -f "test_report.md" ]; then
          echo "report<<EOF" >> $GITHUB_OUTPUT
          cat test-report.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        else
          echo "Error: test_report.md not found"
          exit 1
        fi

    - name: Comment on PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          ## Test Results
          ${{ steps.report.outputs.report }}
        comment_tag: execution